package com.alibou.book.Entity;

public enum OrderDetailStatus {
    ACTIVE, RETURN_REQUESTED, RETURN_APPROVED, RETURNED, REFUNDED,RETURN_RECEIVED,DENY_RETURN,DELIVERED,




    PENDING,
    PROCESSED,
    SHIPPED,

}