spring:
  datasource:
    url: jdbc:mysql://localhost:3306/farm
    username: root
    password: EMMARESCUE
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        ddl-auto: update  # Options: create, create-drop, update, validate, none
        format_sql: true
        default_schema: school
    database:
    database-platform: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: emmanuelderryshare@gmail.com
    password: xkgafkycoljlxvew
    protocol: smtp
    properties:
      mail:
        debug: false
        smtp:
          auth: true
          starttls:
            enable: true       # ✅ corrected
            required: true     # ✅ optional but good to include
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
          ssl:
            trust: smtp.gmail.com
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://localhost:8080/realms/postgres"

application:
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
      jwk-set-uri: http://localhost:8080/realms/postgres/protocol/openid-connect/certs
  security:
    jwt:
      secret-key: 19k2m8GRJSBNzJee6zzNWa43JGkoMS9WsB+vfog3OXQ=
      expiration: 86400000
  file:
    uploads:
      photos-output-path: ./uploads
    upload-dir: ./uploads

server:
  port: 8088

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

mnotify:
  v2:
    url: https://api.mnotify.com/api/sms/quick
    key: oWmpfPGz22BObP6ng9Zjb0Xe4
    sender-id: OPTUMSERV
#  OTC
#Princing configuration

moolre:
  api:
    url: https://api.moolre.com/open/transact/payment
  callback:
    url:  https://7885-41-204-44-244.ngrok-free.app/api/v1/auth/payments/statusWebhook
  account-number: 10638206043532
  username: Mudita
  public-key: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyaWQiOjEwNjM4MiwiZXhwIjoxOTI1MDA5OTk5fQ.TlISuKTOcV_S1WM8LjPeFz9vE_64YNOH6fWKLglq7QY
  webhook:
    secret: 6cd824e6-ea05-42f5-bf30-1d63c06b75a8
price:
  ranges:
    step-size: 50.0
    max-before-plus: 200.0